version: 2
jobs:
  build:
    working_directory: ~/circulate
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - run:
          name: Create Test Directory
          command: mkdir reports
      - run:
          name: Bundle Gems
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
      - run:
          name: Run Rake Task
          command: bundle exec rake circleci --trace
      - store_test_results:
          path: reports/
notify:
  webhooks:
    - url: https://webhooks.gitter.im/e/cf84bd37a43b066fb883